package:
  name: prosail
  version: 2.0.0alpha
  
source:
  git_tag: 2.0.0alpha
  git_url: http://github.com/jgomezdans/prosail.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - backports.functools_lru_cache
    - numba
    - pytest

  run:
    - python
    - numpy
    - scipy
    - backports.functools_lru_cache
    - numba
    - pytest

test:
  imports:
    - prosail

about:
  home: http://github.com/jgomezdans/prosail
  license: 
  summary: "The PROSPECT and SAIL radiative transfer models"
